apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: strimzi
spec:
  interval: 1h
  url: https://strimzi.io/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: strimzi-kafka-operator
spec:
  interval: 1h
  chart:
    spec:
      chart: strimzi-kafka-operator
      version: "0.37.0"
      sourceRef:
        kind: HelmRepository
        name: strimzi
  values:
    watchNamespaces:
      - ventra-messenger-dev