apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  namespace: ventra-messenger-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-cluster-operator
  template:
    metadata:
      labels:
        name: strimzi-cluster-operator
    spec:
      serviceAccountName: strimzi-cluster-operator
      containers:
        - name: strimzi-cluster-operator
          image: quay.io/strimzi/operator:0.37.0
          command: ["/opt/strimzi/bin/cluster_operator_run.sh"]
          args:
            - --watch-namespace=$(STRIMZI_NAMESPACE)
          env:
            - name: STRIMZI_NAMESPACE
              value: ventra-messenger-dev
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_KAFKA_IMAGES
              '3.4.0=quay.io/strimzi/kafka:3.4.0-0.37.0,3.4.1=quay.io/strimzi/kafka:3.4.1-0.37.0,3.5.0=quay.io/strimzi/kafka:3.5.0-0.37.0,3.5.1=quay.io/strimzi/kafka:3.5.1-0.37.0'
            - name: STRIMZI_KAFKA_CONNECT_IMAGES
              '3.4.0=quay.io/strimzi/kafka:3.4.0-0.37.0,3.4.1=quay.io/strimzi/kafka:3.4.1-0.37.0,3.5.0=quay.io/strimzi/kafka:3.5.0-0.37.0,3.5.1=quay.io/strimzi/kafka:3.5.1-0.37.0'
            - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
              '3.4.0=quay.io/strimzi/kafka:3.4.0-0.37.0,3.4.1=quay.io/strimzi/kafka:3.4.1-0.37.0,3.5.0=quay.io/strimzi/kafka:3.5.0-0.37.0,3.5.1=quay.io/strimzi/kafka:3.5.1-0.37.0'
            - name: STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES
              '3.4.0=quay.io/strimzi/kafka:3.4.0-0.37.0,3.4.1=quay.io/strimzi/kafka:3.4.1-0.37.0,3.5.0=quay.io/strimzi/kafka:3.5.0-0.37.0,3.5.1=quay.io/strimzi/kafka:3.5.1-0.37.0'