apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: strimzi-kafka-operator
  namespace: ventra-messenger-dev
spec:
  repo: https://strimzi.io/charts/
  chart: strimzi-kafka-operator
  version: 0.37.0
  targetNamespace: ventra-messenger-dev
  valuesContent: |-
    watchNamespaces:
      - ventra-messenger-dev