apiVersion: v1
  kind: Namespace
  metadata:
    name: ventra-messenger-dev
  ---
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: strimzi-cluster-operator
    namespace: ventra-messenger-dev
  ---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: strimzi-cluster-operator-global
  rules:
    # Keep your existing rules here
    - apiGroups: ["kafka.strimzi.io"]
      resources: ["kafkas", "kafkatopics", "kafkausers", "kafkaconnects", "kafkabridges", "kafkamirrormakers"]
      verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
    # Other rules...
  ---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: strimzi-cluster-operator-binding
  subjects:
    - kind: ServiceAccount
      name: strimzi-cluster-operator
      namespace: ventra-messenger-dev
  roleRef:
    kind: ClusterRole
    name: strimzi-cluster-operator-global
    apiGroup: rbac.authorization.k8s.io