apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --out k8s
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: vm-main-db
  name: vm-main-db
  namespace: default
spec:
  ports:
    - name: "8884"
      port: 8884
      targetPort: 8884
  selector:
    io.kompose.service: vm-main-db
status:
  loadBalancer: {}
