apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --out k8s
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: vm-redis
  name: vm-redis
  namespace: default
spec:
  ports:
    - name: "8885"
      port: 8885
      targetPort: 8885
  selector:
    io.kompose.service: vm-redis
status:
  loadBalancer: {}
