apiVersion: v1
kind: ConfigMap
metadata:
  name: strimzi-platform-features
  namespace: ventra-messenger-dev
data:
  strimzi-platform-features.json: |
    {
      "kubernetesVersion": "v1.27.0",
      "kubernetesMajorVersion": 1,
      "kubernetesMinorVersion": 27,
      "ocpVersion": "0",
      "strimziVersion": "0.37.0",
      "kubernetesDistribution": "k3s"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  namespace: ventra-messenger-dev
spec:
  template:
    spec:
      containers:
        - name: strimzi-cluster-operator
          env:
            - name: STRIMZI_PLATFORM_FEATURES_FILE
              value: "/opt/strimzi/custom-config/strimzi-platform-features.json"
          volumeMounts:
            - name: platform-features
              mountPath: "/opt/strimzi/custom-config"
      volumes:
        - name: platform-features
          configMap:
            name: strimzi-platform-features