apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-zookeeper-0
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-zookeeper-storage
  local:
    path: /mnt/zookeeper-data-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - __NODE_NAME__ # gets replaced by the node name where the PV is created