apiVersion: apps/v1
kind: Deployment
metadata:
  name: ventra-messenger
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: ventra-messenger
        env:
        - name: APP_ENV
          value: "single-node-dev"
