apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml --out k8sFiles
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka
  name: kafka
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml --out k8sFiles
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/backend-ventra-net: "true"
        io.kompose.service: kafka
    spec:
      containers:
        - env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: SSL://kafka:9093
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_LISTENERS
              value: SSL://0.0.0.0:9093
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_SECURITY_INTER_BROKER_PROTOCOL
              value: SSL
            - name: KAFKA_SSL_CLIENT_AUTH
              value: required
            - name: KAFKA_SSL_KEYSTORE_LOCATION
              value: /etc/kafka/secrets/kafka.keystore.jks
            - name: KAFKA_SSL_KEYSTORE_PASSWORD
              value: changeit
            - name: KAFKA_SSL_KEY_PASSWORD
              value: changeit
            - name: KAFKA_SSL_TRUSTSTORE_LOCATION
              value: /etc/kafka/secrets/kafka.truststore.jks
            - name: KAFKA_SSL_TRUSTSTORE_PASSWORD
              value: changeit
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: kafka-zookeeper:2181
          image: confluentinc/cp-kafka:7.5.0
          name: kafka
          ports:
            - containerPort: 9092
              hostPort: 9092
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
