apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml --out k8sFiles
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka-init
  name: kafka-init
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka-init
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml --out k8sFiles
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/backend-ventra-net: 'true'
        io.kompose.service: kafka-init
    spec:
      containers:
        - env:
            - name: VAULT_ADDR
              value: https://vm-vault:8200
          image: kafka-init
          name: kafka-init
          resources: {}
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
status: {}
