apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml --out k8sFiles
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: vm-main-db
  name: vm-main-db
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vm-main-db
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml --out k8sFiles
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/backend-ventra-net: "true"
        io.kompose.service: vm-main-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: main_db
            - name: POSTGRES_PASSWORD
              value: testPassword1234
            - name: POSTGRES_USER
              value: dev
          image: postgres:15
          name: vm-main-db
          ports:
            - containerPort: 8890
              hostPort: 8890
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
