apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml --out k8sFiles
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: vm-redis
  name: vm-redis
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vm-redis
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml --out k8sFiles
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/backend-ventra-net: "true"
        io.kompose.service: vm-redis
    spec:
      containers:
        - image: redis:7
          name: vm-redis
          ports:
            - containerPort: 8891
              hostPort: 8891
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
