apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml --out k8sFiles
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.network/backend-ventra-net: "true"
    io.kompose.service: vm-vault-init
  name: vm-vault-init
  namespace: default
spec:
  containers:
    - env:
        - name: VAULT_ADDR
          value: https://vm-vault:8200
      image: vm-vault-init
      name: vm-vault-init
      resources: {}
  restartPolicy: OnFailure
status: {}
