apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-monitor
  labels:
    app: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  endpoints:
    - port: client
      path: /metrics
      interval: 30s