apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  ports:
    - name: client
      port: 9092
      protocol: TCP
    - name: controller
      port: 9093
      protocol: TCP
  clusterIP: None
  selector:
    app: kafka