apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-cert
  namespace: cert-manager
spec:
  secretName: test-tls
  issuerRef:
    name: vault-issuer
    kind: Issuer
  commonName: test.ventra.cluster
  dnsNames:
    - test.ventra.cluster
  duration: 24h
  renewBefore: 6h
