server:
  standalone:
    enabled: true
    config: |
      ui = true

      listener "tcp" {
        address = "0.0.0.0:8200"
        cluster_address = "0.0.0.0:8201"
        tls_disable = true
      }

      storage "file" {
        path = "/vault/data"
      }

      disable_mlock = true

  dataStorage:
    enabled: true
    size: 10Gi
    accessMode: ReadWriteOnce

ui:
  enabled: true
  service:
    enabled: true
    type: NodePort
    nodePort: 30200
    port: 8200

injector:
  enabled: false

ha:
  enabled: false
