// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: redis.proto

package gRPC

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Generic response for status operations.
type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_redis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_redis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_redis_proto_rawDescGZIP(), []int{0}
}

func (x *StatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Used to identify a user.
type UserID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserID) Reset() {
	*x = UserID{}
	mi := &file_redis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserID) ProtoMessage() {}

func (x *UserID) ProtoReflect() protoreflect.Message {
	mi := &file_redis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserID.ProtoReflect.Descriptor instead.
func (*UserID) Descriptor() ([]byte, []int) {
	return file_redis_proto_rawDescGZIP(), []int{1}
}

func (x *UserID) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Request to set a user's status.
type UserStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // online, offline, afk
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserStatusRequest) Reset() {
	*x = UserStatusRequest{}
	mi := &file_redis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatusRequest) ProtoMessage() {}

func (x *UserStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatusRequest.ProtoReflect.Descriptor instead.
func (*UserStatusRequest) Descriptor() ([]byte, []int) {
	return file_redis_proto_rawDescGZIP(), []int{2}
}

func (x *UserStatusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Response with the user's current status.
type UserStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserStatusResponse) Reset() {
	*x = UserStatusResponse{}
	mi := &file_redis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatusResponse) ProtoMessage() {}

func (x *UserStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_redis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatusResponse.ProtoReflect.Descriptor instead.
func (*UserStatusResponse) Descriptor() ([]byte, []int) {
	return file_redis_proto_rawDescGZIP(), []int{3}
}

func (x *UserStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Request to set the API-ID for a user session.
type SetUserSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Api           string                 `protobuf:"bytes,2,opt,name=api,proto3" json:"api,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserSessionRequest) Reset() {
	*x = SetUserSessionRequest{}
	mi := &file_redis_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserSessionRequest) ProtoMessage() {}

func (x *SetUserSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redis_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserSessionRequest.ProtoReflect.Descriptor instead.
func (*SetUserSessionRequest) Descriptor() ([]byte, []int) {
	return file_redis_proto_rawDescGZIP(), []int{4}
}

func (x *SetUserSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetUserSessionRequest) GetApi() string {
	if x != nil {
		return x.Api
	}
	return ""
}

// Request to get the API-ID for a user session.
type GetUserSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSessionRequest) Reset() {
	*x = GetUserSessionRequest{}
	mi := &file_redis_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSessionRequest) ProtoMessage() {}

func (x *GetUserSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redis_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSessionRequest.ProtoReflect.Descriptor instead.
func (*GetUserSessionRequest) Descriptor() ([]byte, []int) {
	return file_redis_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Response with the API-ID for a user session.
type GetUserSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Api           string                 `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSessionResponse) Reset() {
	*x = GetUserSessionResponse{}
	mi := &file_redis_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSessionResponse) ProtoMessage() {}

func (x *GetUserSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_redis_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSessionResponse.ProtoReflect.Descriptor instead.
func (*GetUserSessionResponse) Descriptor() ([]byte, []int) {
	return file_redis_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserSessionResponse) GetApi() string {
	if x != nil {
		return x.Api
	}
	return ""
}

// Request to update or increment a metric.
type MetricUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricUpdateRequest) Reset() {
	*x = MetricUpdateRequest{}
	mi := &file_redis_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricUpdateRequest) ProtoMessage() {}

func (x *MetricUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redis_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricUpdateRequest.ProtoReflect.Descriptor instead.
func (*MetricUpdateRequest) Descriptor() ([]byte, []int) {
	return file_redis_proto_rawDescGZIP(), []int{7}
}

func (x *MetricUpdateRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MetricUpdateRequest) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// Request to reset a metric.
type MetricKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricKeyRequest) Reset() {
	*x = MetricKeyRequest{}
	mi := &file_redis_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricKeyRequest) ProtoMessage() {}

func (x *MetricKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redis_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricKeyRequest.ProtoReflect.Descriptor instead.
func (*MetricKeyRequest) Descriptor() ([]byte, []int) {
	return file_redis_proto_rawDescGZIP(), []int{8}
}

func (x *MetricKeyRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// Request to get values for a list of metric keys.
type GetMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsRequest) Reset() {
	*x = GetMetricsRequest{}
	mi := &file_redis_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsRequest) ProtoMessage() {}

func (x *GetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redis_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_redis_proto_rawDescGZIP(), []int{9}
}

func (x *GetMetricsRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

// Response with a map of metric keys and their values.
type MetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       map[string]int64       `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_redis_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_redis_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_redis_proto_rawDescGZIP(), []int{10}
}

func (x *MetricsResponse) GetMetrics() map[string]int64 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// Empty message for requests that need no parameters.
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_redis_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_redis_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_redis_proto_rawDescGZIP(), []int{11}
}

var File_redis_proto protoreflect.FileDescriptor

const file_redis_proto_rawDesc = "" +
	"\n" +
	"\vredis.proto\x12\bredisApi\"D\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"!\n" +
	"\x06UserID\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"D\n" +
	"\x11UserStatusRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\",\n" +
	"\x12UserStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"B\n" +
	"\x15SetUserSessionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x10\n" +
	"\x03api\x18\x02 \x01(\tR\x03api\"0\n" +
	"\x15GetUserSessionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"*\n" +
	"\x16GetUserSessionResponse\x12\x10\n" +
	"\x03api\x18\x01 \x01(\tR\x03api\"=\n" +
	"\x13MetricUpdateRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value\"$\n" +
	"\x10MetricKeyRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"'\n" +
	"\x11GetMetricsRequest\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\"\x8f\x01\n" +
	"\x0fMetricsResponse\x12@\n" +
	"\ametrics\x18\x01 \x03(\v2&.redisApi.MetricsResponse.MetricsEntryR\ametrics\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\a\n" +
	"\x05Empty2\x9b\x05\n" +
	"\x11UserStatusService\x12F\n" +
	"\rSetUserStatus\x12\x1b.redisApi.UserStatusRequest\x1a\x18.redisApi.StatusResponse\x12?\n" +
	"\rGetUserStatus\x12\x10.redisApi.UserID\x1a\x1c.redisApi.UserStatusResponse\x12K\n" +
	"\x0eSetUserSession\x12\x1f.redisApi.SetUserSessionRequest\x1a\x18.redisApi.StatusResponse\x12S\n" +
	"\x0eGetUserSession\x12\x1f.redisApi.GetUserSessionRequest\x1a .redisApi.GetUserSessionResponse\x12J\n" +
	"\x0fIncrementMetric\x12\x1d.redisApi.MetricUpdateRequest\x1a\x18.redisApi.StatusResponse\x12G\n" +
	"\fUpdateMetric\x12\x1d.redisApi.MetricUpdateRequest\x1a\x18.redisApi.StatusResponse\x12C\n" +
	"\vResetMetric\x12\x1a.redisApi.MetricKeyRequest\x1a\x18.redisApi.StatusResponse\x12D\n" +
	"\n" +
	"GetMetrics\x12\x1b.redisApi.GetMetricsRequest\x1a\x19.redisApi.MetricsResponse\x12;\n" +
	"\rGetAllMetrics\x12\x0f.redisApi.Empty\x1a\x19.redisApi.MetricsResponseB\x13Z\x11../redisApi;protob\x06proto3"

var (
	file_redis_proto_rawDescOnce sync.Once
	file_redis_proto_rawDescData []byte
)

func file_redis_proto_rawDescGZIP() []byte {
	file_redis_proto_rawDescOnce.Do(func() {
		file_redis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_redis_proto_rawDesc), len(file_redis_proto_rawDesc)))
	})
	return file_redis_proto_rawDescData
}

var file_redis_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_redis_proto_goTypes = []any{
	(*StatusResponse)(nil),         // 0: redisApi.StatusResponse
	(*UserID)(nil),                 // 1: redisApi.UserID
	(*UserStatusRequest)(nil),      // 2: redisApi.UserStatusRequest
	(*UserStatusResponse)(nil),     // 3: redisApi.UserStatusResponse
	(*SetUserSessionRequest)(nil),  // 4: redisApi.SetUserSessionRequest
	(*GetUserSessionRequest)(nil),  // 5: redisApi.GetUserSessionRequest
	(*GetUserSessionResponse)(nil), // 6: redisApi.GetUserSessionResponse
	(*MetricUpdateRequest)(nil),    // 7: redisApi.MetricUpdateRequest
	(*MetricKeyRequest)(nil),       // 8: redisApi.MetricKeyRequest
	(*GetMetricsRequest)(nil),      // 9: redisApi.GetMetricsRequest
	(*MetricsResponse)(nil),        // 10: redisApi.MetricsResponse
	(*Empty)(nil),                  // 11: redisApi.Empty
	nil,                            // 12: redisApi.MetricsResponse.MetricsEntry
}
var file_redis_proto_depIdxs = []int32{
	12, // 0: redisApi.MetricsResponse.metrics:type_name -> redisApi.MetricsResponse.MetricsEntry
	2,  // 1: redisApi.UserStatusService.SetUserStatus:input_type -> redisApi.UserStatusRequest
	1,  // 2: redisApi.UserStatusService.GetUserStatus:input_type -> redisApi.UserID
	4,  // 3: redisApi.UserStatusService.SetUserSession:input_type -> redisApi.SetUserSessionRequest
	5,  // 4: redisApi.UserStatusService.GetUserSession:input_type -> redisApi.GetUserSessionRequest
	7,  // 5: redisApi.UserStatusService.IncrementMetric:input_type -> redisApi.MetricUpdateRequest
	7,  // 6: redisApi.UserStatusService.UpdateMetric:input_type -> redisApi.MetricUpdateRequest
	8,  // 7: redisApi.UserStatusService.ResetMetric:input_type -> redisApi.MetricKeyRequest
	9,  // 8: redisApi.UserStatusService.GetMetrics:input_type -> redisApi.GetMetricsRequest
	11, // 9: redisApi.UserStatusService.GetAllMetrics:input_type -> redisApi.Empty
	0,  // 10: redisApi.UserStatusService.SetUserStatus:output_type -> redisApi.StatusResponse
	3,  // 11: redisApi.UserStatusService.GetUserStatus:output_type -> redisApi.UserStatusResponse
	0,  // 12: redisApi.UserStatusService.SetUserSession:output_type -> redisApi.StatusResponse
	6,  // 13: redisApi.UserStatusService.GetUserSession:output_type -> redisApi.GetUserSessionResponse
	0,  // 14: redisApi.UserStatusService.IncrementMetric:output_type -> redisApi.StatusResponse
	0,  // 15: redisApi.UserStatusService.UpdateMetric:output_type -> redisApi.StatusResponse
	0,  // 16: redisApi.UserStatusService.ResetMetric:output_type -> redisApi.StatusResponse
	10, // 17: redisApi.UserStatusService.GetMetrics:output_type -> redisApi.MetricsResponse
	10, // 18: redisApi.UserStatusService.GetAllMetrics:output_type -> redisApi.MetricsResponse
	10, // [10:19] is the sub-list for method output_type
	1,  // [1:10] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_redis_proto_init() }
func file_redis_proto_init() {
	if File_redis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_redis_proto_rawDesc), len(file_redis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_redis_proto_goTypes,
		DependencyIndexes: file_redis_proto_depIdxs,
		MessageInfos:      file_redis_proto_msgTypes,
	}.Build()
	File_redis_proto = out.File
	file_redis_proto_goTypes = nil
	file_redis_proto_depIdxs = nil
}
