name: Qodana C++ Analysis

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  qodana-cpp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Qodana Scan (C++)
        uses: JetBrains/qodana-action@v2024.1
        with:
          project-dir: QTClient
          linter: cpp
