name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Build custom Qodana image
        run: docker build -t my-qodana-cpp-custom -f Dockerfile .
      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2025.1
        with:
          args: --linter my-qodana-cpp-custom
          pr-mode: false
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_1469171812 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'